# This is a basic example Blueprint for a Django web service and
# the Render Postgres database it connects to.
services:
  - type: web # A Python web service named django-app running on a free instance
    plan: free
    name: app-modulo-soporte
    runtime: docker
    repo: https://github.com/CrissRMFI/TPG-PSA.git
    branch: 'feature/deploy'
    autoDeployTrigger: commit

    envVars:
      - key: EXT_API_CLIENTS
        value: https://anypoint.mulesoft.com/mocking/api/v1/sources/exchange/assets/754f50e8-20d8-4223-bbdc-56d50131d0ae/clientes-psa/1.0.0/m/api/clientes
      - key: EXT_API_RESOURCES
        value: https://anypoint.mulesoft.com/mocking/api/v1/sources/exchange/assets/32c8fe38-22a6-4fbb-b461-170dfac937e4/recursos-api/1.0.1/m/recursos
      - key: API_CONTEXT_PATH
        value: /support-module
      - key: DB_URL
        fromDatabase:
          name: modulo_soporte_db
          property: connectionString
      - key: DB_USER_NAME
        fromDatabase:
          name: modulo_soporte_db
          property: user 
      - key: DB_PASSWORD
        fromDatabase:
          name: modulo_soporte_db
          property: password 
      - key: DB_PORT
        fromDatabase:
          name: modulo_soporte_db
          property: port


databases:
    - name: modulo_soporte_db
      plan: free